In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"name": ['Asad', 'Bila', 'Ali'], "age": [25, 30, 35]})
print(df)

   name  age
0  Asad   25
1  Bila   30
2   Ali   35

In [3]:
df["name"]
df["age"]

0    25
1    30
2    35
Name: age, dtype: int64

In [4]:
df1 = pd.read_csv("Housing.csv")
print(df1)

        price    area  bedrooms  bathrooms  stories mainroad guestroom  \
0    13300000  7420.0       4.0          2        3      yes        no
1    12250000  8960.0       4.0          4        4      yes       NaN
2    12250000  9960.0       NaN          2        2      yes        no
3    12215000     NaN       4.0          2        2      yes        no
4    11410000  7420.0       4.0          1        2      yes       yes
..        ...     ...       ...        ...      ...      ...       ...
540   1820000  3000.0       2.0          1        1      yes        no
541   1767150  2400.0       3.0          1        1       no        no
542   1750000  3620.0       2.0          1        1      yes        no
543   1750000  2910.0       3.0          1        1       no        no
544   1750000  3850.0       3.0          1        2      yes        no

    basement hotwaterheating airconditioning  parking prefarea  \
0         no              no             yes        2      yes
1         no             NaN             yes        3       no
2        yes              no              no        2      yes
3        yes              no             yes        3      yes
4        yes              no             yes        2       no
..       ...             ...             ...      ...      ...
540      yes              no              no        2       no
541       no              no              no        0       no
542       no              no              no        0       no
543       no              no              no        0       no
544       no              no              no        0       no

    furnishingstatus
0          furnished
1          furnished
2     semi-furnished
3          furnished
4          furnished
..               ...
540      unfurnished
541   semi-furnished
542      unfurnished
543        furnished
544      unfurnished

[545 rows x 13 columns]

In [5]:
df1.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420.0,4.0,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960.0,4.0,4,4,yes,NaN,no,NaN,yes,3,no,furnished
2,12250000,9960.0,NaN,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,NaN,4.0,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420.0,4.0,1,2,yes,yes,yes,no,yes,2,no,furnished

In [6]:
df2 = pd.read_csv("Housing.csv")
print(df2.head())

      price    area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420.0       4.0          2        3      yes        no       no
1  12250000  8960.0       4.0          4        4      yes       NaN       no
2  12250000  9960.0       NaN          2        2      yes        no      yes
3  12215000     NaN       4.0          2        2      yes        no      yes
4  11410000  7420.0       4.0          1        2      yes       yes      yes

  hotwaterheating airconditioning  parking prefarea furnishingstatus
0              no             yes        2      yes        furnished
1             NaN             yes        3       no        furnished
2              no              no        2      yes   semi-furnished
3              no             yes        3      yes        furnished
4              no             yes        2       no        furnished

In [7]:
df2.dropna(inplace=True)
df2.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420.0,4.0,2,3,yes,no,no,no,yes,2,yes,furnished
4,11410000,7420.0,4.0,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500.0,3.0,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580.0,4.0,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200.0,5.0,3,2,yes,no,no,no,no,0,no,unfurnished

In [8]:
df2["price"].head(5)

0    13300000
4    11410000
5    10850000
6    10150000
7    10150000
Name: price, dtype: int64

In [9]:
df2.info()

<class 'pandas.DataFrame'>
Index: 542 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             542 non-null    int64
 1   area              542 non-null    float64
 2   bedrooms          542 non-null    float64
 3   bathrooms         542 non-null    int64
 4   stories           542 non-null    int64
 5   mainroad          542 non-null    str
 6   guestroom         542 non-null    str
 7   basement          542 non-null    str
 8   hotwaterheating   542 non-null    str
 9   airconditioning   542 non-null    str
 10  parking           542 non-null    int64
 11  prefarea          542 non-null    str
 12  furnishingstatus  542 non-null    str
dtypes: float64(2), int64(4), str(7)
memory usage: 59.3 KB

In [10]:
df2["price"].head(15)

0     13300000
4     11410000
5     10850000
6     10150000
7     10150000
8      9870000
9      9800000
10     9800000
11     9681000
12     9310000
13     9240000
14     9240000
15     9100000
16     9100000
17     8960000
Name: price, dtype: int64

In [11]:
df2["price"].tail(5)

540    1820000
541    1767150
542    1750000
543    1750000
544    1750000
Name: price, dtype: int64

In [12]:
df2["price"].head(15)

0     13300000
4     11410000
5     10850000
6     10150000
7     10150000
8      9870000
9      9800000
10     9800000
11     9681000
12     9310000
13     9240000
14     9240000
15     9100000
16     9100000
17     8960000
Name: price, dtype: int64

In [13]:
df1 = pd.read_csv("Housing.csv", nrows=50) 
print(df1)

       price     area  bedrooms  bathrooms  stories mainroad guestroom  \
0   13300000   7420.0       4.0          2        3      yes        no
1   12250000   8960.0       4.0          4        4      yes       NaN
2   12250000   9960.0       NaN          2        2      yes        no
3   12215000      NaN       4.0          2        2      yes        no
4   11410000   7420.0       4.0          1        2      yes       yes
5   10850000   7500.0       3.0          3        1      yes        no
6   10150000   8580.0       4.0          3        4      yes        no
7   10150000  16200.0       5.0          3        2      yes        no
8    9870000   8100.0       4.0          1        2      yes       yes
9    9800000   5750.0       3.0          2        4      yes       yes
10   9800000  13200.0       3.0          1        2      yes        no
11   9681000   6000.0       4.0          3        2      yes       yes
12   9310000   6550.0       4.0          2        2      yes        no
13   9240000   3500.0       4.0          2        2      yes        no
14   9240000   7800.0       3.0          2        2      yes        no
15   9100000   6000.0       4.0          1        2      yes        no
16   9100000   6600.0       4.0          2        2      yes       yes
17   8960000   8500.0       3.0          2        4      yes        no
18   8890000   4600.0       3.0          2        2      yes       yes
19   8855000   6420.0       3.0          2        2      yes        no
20   8750000   4320.0       3.0          1        2      yes        no
21   8680000   7155.0       3.0          2        1      yes       yes
22   8645000   8050.0       3.0          1        1      yes       yes
23   8645000   4560.0       3.0          2        2      yes       yes
24   8575000   8800.0       3.0          2        2      yes        no
25   8540000   6540.0       4.0          2        2      yes       yes
26   8463000   6000.0       3.0          2        4      yes       yes
27   8400000   8875.0       3.0          1        1      yes        no
28   8400000   7950.0       5.0          2        2      yes        no
29   8400000   5500.0       4.0          2        2      yes        no
30   8400000   7475.0       3.0          2        4      yes        no
31   8400000   7000.0       3.0          1        4      yes        no
32   8295000   4880.0       4.0          2        2      yes        no
33   8190000   5960.0       3.0          3        2      yes       yes
34   8120000   6840.0       5.0          1        2      yes       yes
35   8080940   7000.0       3.0          2        4      yes        no
36   8043000   7482.0       3.0          2        3      yes        no
37   7980000   9000.0       4.0          2        4      yes        no
38   7962500   6000.0       3.0          1        4      yes       yes
39   7910000   6000.0       4.0          2        4      yes        no
40   7875000   6550.0       3.0          1        2      yes        no
41   7840000   6360.0       3.0          2        4      yes        no
42   7700000   6480.0       3.0          2        4      yes        no
43   7700000   6000.0       4.0          2        4      yes        no
44   7560000   6000.0       4.0          2        4      yes        no
45   7560000   6000.0       3.0          2        3      yes        no
46   7525000   6000.0       3.0          2        4      yes        no
47   7490000   6600.0       3.0          1        4      yes        no
48   7455000   4300.0       3.0          2        2      yes        no
49   7420000   7440.0       3.0          2        1      yes       yes

   basement hotwaterheating airconditioning  parking prefarea furnishingstatus
0        no              no             yes        2      yes        furnished
1        no             NaN             yes        3       no        furnished
2       yes              no              no        2      yes   semi-furnished
3       yes              no             yes        3      yes        furnished
4       yes              no             yes        2       no        furnished
5       yes              no             yes        2      yes   semi-furnished
6        no              no             yes        2      yes   semi-furnished
7        no              no              no        0       no      unfurnished
8       yes              no             yes        2      yes        furnished
9        no              no             yes        1      yes      unfurnished
10      yes              no             yes        2      yes        furnished
11      yes             yes              no        2       no   semi-furnished
12       no              no             yes        1      yes   semi-furnished
13       no             yes              no        2       no        furnished
14       no              no              no        0      yes   semi-furnished
15      yes              no              no        2       no   semi-furnished
16      yes              no             yes        1      yes      unfurnished
17       no              no             yes        2       no        furnished
18       no              no             yes        2       no        furnished
19       no              no             yes        1      yes   semi-furnished
20      yes             yes              no        2       no   semi-furnished
21      yes              no             yes        2       no      unfurnished
22      yes              no             yes        1       no        furnished
23      yes              no             yes        1       no        furnished
24       no              no             yes        2       no        furnished
25      yes              no             yes        2      yes        furnished
26      yes              no             yes        0      yes   semi-furnished
27       no              no              no        1       no   semi-furnished
28      yes             yes              no        2       no      unfurnished
29      yes              no             yes        1      yes   semi-furnished
30       no              no             yes        2       no      unfurnished
31       no              no             yes        2       no   semi-furnished
32       no              no             yes        1      yes        furnished
33      yes              no              no        1       no      unfurnished
34      yes              no             yes        1       no        furnished
35       no              no             yes        2       no        furnished
36       no             yes              no        1      yes        furnished
37       no              no             yes        2       no        furnished
38       no              no             yes        2       no      unfurnished
39       no              no             yes        1       no   semi-furnished
40      yes              no             yes        0      yes        furnished
41       no              no             yes        0      yes        furnished
42       no              no             yes        2       no      unfurnished
43       no              no              no        2       no   semi-furnished
44       no              no             yes        1       no        furnished
45       no              no             yes        0       no   semi-furnished
46       no              no             yes        1       no        furnished
47       no              no             yes        3      yes        furnished
48      yes              no              no        1       no      unfurnished
49      yes              no             yes        0      yes   semi-furnished

In [14]:
print(df2["price"].head(5) ,df2["bedrooms"].head(5))

0    13300000
4    11410000
5    10850000
6    10150000
7    10150000
Name: price, dtype: int64 0    4.0
4    4.0
5    3.0
6    4.0
7    5.0
Name: bedrooms, dtype: float64

In [15]:
df2.iloc[1]

price                11410000
area                   7420.0
bedrooms                  4.0
bathrooms                   1
stories                     2
mainroad                  yes
guestroom                 yes
basement                  yes
hotwaterheating            no
airconditioning           yes
parking                     2
prefarea                   no
furnishingstatus    furnished
Name: 4, dtype: object

In [16]:
df2.iloc[40:100]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
43,7700000,6000.0,4.0,2,4,yes,no,no,no,no,2,no,semi-furnished
44,7560000,6000.0,4.0,2,4,yes,no,no,no,yes,1,no,furnished
45,7560000,6000.0,3.0,2,3,yes,no,no,no,yes,0,no,semi-furnished
46,7525000,6000.0,3.0,2,4,yes,no,no,no,yes,1,no,furnished
47,7490000,6600.0,3.0,1,4,yes,no,no,no,yes,3,yes,furnished
48,7455000,4300.0,3.0,2,2,yes,no,yes,no,no,1,no,unfurnished
49,7420000,7440.0,3.0,2,1,yes,yes,yes,no,yes,0,yes,semi-furnished
50,7420000,7440.0,3.0,2,4,yes,no,no,no,no,1,yes,unfurnished
51,7420000,6325.0,3.0,1,4,yes,no,no,no,yes,1,no,unfurnished
52,7350000,6000.0,4.0,2,4,yes,yes,no,no,yes,1,no,furnished
53,7350000,5150.0,3.0,2,4,yes,no,no,no,yes,2,no,semi-furnished
54,7350000,6000.0,3.0,2,2,yes,yes,no,no,yes,1,no,semi-furnished
55,7350000,6000.0,3.0,1,2,yes,no,no,no,yes,1,no,unfurnished
56,7343000,11440.0,4.0,1,2,yes,no,yes,no,no,1,yes,semi-furnished
57,7245000,9000.0,4.0,2,4,yes,yes,no,no,yes,1,yes,furnished
58,7210000,7680.0,4.0,2,4,yes,yes,no,no,yes,1,no,semi-furnished
59,7210000,6000.0,3.0,2,4,yes,yes,no,no,yes,1,no,furnished
60,7140000,6000.0,3.0,2,2,yes,yes,no,no,no,1,no,semi-furnished
61,7070000,8880.0,2.0,1,1,yes,no,no,no,yes,1,no,semi-furnished
62,7070000,6240.0,4.0,2,2,yes,no,no,no,yes,1,no,furnished
63,7035000,6360.0,4.0,2,3,yes,no,no,no,yes,2,yes,furnished
64,7000000,11175.0,3.0,1,1,yes,no,yes,no,yes,1,yes,furnished
65,6930000,8880.0,3.0,2,2,yes,no,yes,no,yes,1,no,furnished
66,6930000,13200.0,2.0,1,1,yes,no,yes,yes,no,1,no,furnished
67,6895000,7700.0,3.0,2,1,yes,no,no,no,no,2,no,unfurnished
68,6860000,6000.0,3.0,1,1,yes,no,no,no,yes,1,no,furnished
69,6790000,12090.0,4.0,2,2,yes,no,no,no,no,2,yes,furnished
70,6790000,4000.0,3.0,2,2,yes,no,yes,no,yes,0,yes,semi-furnished
71,6755000,6000.0,4.0,2,4,yes,no,no,no,yes,0,no,unfurnished
72,6720000,5020.0,3.0,1,4,yes,no,no,no,yes,0,yes,unfurnished
73,6685000,6600.0,2.0,2,4,yes,no,yes,no,no,0,yes,furnished
74,6650000,4040.0,3.0,1,2,yes,no,yes,yes,no,1,no,furnished
75,6650000,4260.0,4.0,2,2,yes,no,no,yes,no,0,no,semi-furnished
76,6650000,6420.0,3.0,2,3,yes,no,no,no,yes,0,yes,furnished
77,6650000,6500.0,3.0,2,3,yes,no,no,no,yes,0,yes,furnished
78,6650000,5700.0,3.0,1,1,yes,yes,yes,no,yes,2,yes,furnished
79,6650000,6000.0,3.0,2,3,yes,yes,no,no,yes,0,no,furnished
80,6629000,6000.0,3.0,1,2,yes,no,no,yes,no,1,yes,semi-furnished
81,6615000,4000.0,3.0,2,2,yes,no,yes,no,yes,1,no,semi-furnished
82,6615000,10500.0,3.0,2,1,yes,no,yes,no,yes,1,yes,furnished
83,6580000,6000.0,3.0,2,4,yes,no,no,no,yes,0,no,semi-furnished
84,6510000,3760.0,3.0,1,2,yes,no,no,yes,no,2,no,semi-furnished
85,6510000,8250.0,3.0,2,3,yes,no,no,no,yes,0,no,furnished
86,6510000,6670.0,3.0,1,3,yes,no,yes,no,no,0,yes,unfurnished
87,6475000,3960.0,3.0,1,1,yes,no,yes,no,no,2,no,semi-furnished
88,6475000,7410.0,3.0,1,1,yes,yes,yes,no,yes,2,yes,unfurnished
89,6440000,8580.0,5.0,3,2,yes,no,no,no,no,2,no,furnished
90,6440000,5000.0,3.0,1,2,yes,no,no,no,yes,0,no,semi-furnished
91,6419000,6750.0,2.0,1,1,yes,yes,yes,no,no,2,yes,furnished
92,6405000,4800.0,3.0,2,4,yes,yes,no,no,yes,0,no,furnished
93,6300000,7200.0,3.0,2,1,yes,no,yes,no,yes,3,no,semi-furnished
94,6300000,6000.0,4.0,2,4,yes,no,no,no,no,1,no,semi-furnished
95,6300000,4100.0,3.0,2,3,yes,no,no,no,yes,2,no,semi-furnished
96,6300000,9000.0,3.0,1,1,yes,no,yes,no,no,1,yes,furnished
97,6300000,6400.0,3.0,1,1,yes,yes,yes,no,yes,1,yes,semi-furnished
98,6293000,6600.0,3.0,2,3,yes,no,no,no,yes,0,yes,unfurnished
99,6265000,6000.0,4.0,1,3,yes,yes,yes,no,no,0,yes,unfurnished
100,6230000,6600.0,3.0,2,1,yes,no,yes,no,yes,0,yes,unfurnished
101,6230000,5500.0,3.0,1,3,yes,no,no,no,no,1,yes,unfurnished
102,6195000,5500.0,3.0,2,4,yes,yes,no,no,yes,1,no,semi-furnished

In [17]:
df1.loc[0:5,["price","bedrooms"]]

      price  bedrooms
0  13300000       4.0
1  12250000       4.0
2  12250000       NaN
3  12215000       4.0
4  11410000       4.0
5  10850000       3.0

In [18]:
# Fillna is used to fill the missing values in the dataframe with a specified value. In this case, we are filling the missing values in df2 with 5.0.

df2.fillna(5.0,inplace=True)
print(df2.head())

      price     area  bedrooms  bathrooms  stories mainroad guestroom  \
0  13300000   7420.0       4.0          2        3      yes        no
4  11410000   7420.0       4.0          1        2      yes       yes
5  10850000   7500.0       3.0          3        1      yes        no
6  10150000   8580.0       4.0          3        4      yes        no
7  10150000  16200.0       5.0          3        2      yes        no

  basement hotwaterheating airconditioning  parking prefarea furnishingstatus
0       no              no             yes        2      yes        furnished
4      yes              no             yes        2       no        furnished
5      yes              no             yes        2      yes   semi-furnished
6       no              no             yes        2      yes   semi-furnished
7       no              no              no        0       no      unfurnished

# Projects

In [19]:
# Student marks analysis

import numpy as np
import pandas as pd

names = ["Ali", "Bilal", "Ch saad", "Adil", "Asim"]
marks = np.array([80,90,85,70,95])

df = pd.DataFrame({"Name": names, "Marks": marks})
print(df)

      Name  Marks
0      Ali     80
1    Bilal     90
2  Ch saad     85
3     Adil     70
4     Asim     95

In [20]:
avg = df["Marks"].mean()
avg

np.float64(84.0)

In [21]:
max = df["Marks"].max()
max

np.int64(95)

In [22]:
min = df["Marks"].min()
min

np.int64(70)

In [23]:
pass1 = df[df["Marks"] >= 80]
print(pass1)

      Name  Marks
0      Ali     80
1    Bilal     90
2  Ch saad     85
4     Asim     95

In [24]:
# Sales Data Analysis

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct",None, "Dec"]
sales = np.array([1000, 1500, 1200, 1800, 2000,None, 2500, 2200, 3000, 2800, 3500, 4000])
df_sales = pd.DataFrame({"Month": months, "Sales": sales})
print(df_sales)

   Month Sales
0    Jan  1000
1    Feb  1500
2    Mar  1200
3    Apr  1800
4    May  2000
5    Jun  None
6    Jul  2500
7    Aug  2200
8    Sep  3000
9    Oct  2800
10   NaN  3500
11   Dec  4000

In [25]:

months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct",None, "Dec"]
sales = np.array([1000, 1500, 1200, 1800, 2000,None, 2500, 2200, 2800, 3000, 3500, 4000])
df_sales = pd.DataFrame({"Month": months, "Sales": sales})
df_sales.dropna(inplace=True)
print(df_sales)

   Month Sales
0    Jan  1000
1    Feb  1500
2    Mar  1200
3    Apr  1800
4    May  2000
6    Jul  2500
7    Aug  2200
8    Sep  2800
9    Oct  3000
11   Dec  4000

In [26]:
avg1 = df_sales["Sales"].mean()
print("Average Sales:", avg1)

max1 = df_sales["Sales"].max()
print("Maximum Sales:", max1)

min1 = df_sales["Sales"].min()
print("Minimum Sales:", min1)

best_month = df_sales[df_sales["Sales"] == max1]
print("Best Month for sales:", best_month)

best_month = df_sales[df_sales["Sales"] == min1]
print("Best Month for sales:", best_month)

best_month =df_sales.loc[df_sales["Sales"].idxmax(), "Month"]
print("Best Month for sales:", best_month)

best_month =df_sales.loc[df_sales["Sales"].idxmin(), "Month"]
print("Best Month for sales:", best_month)

Average Sales: 2200.0
Maximum Sales: 4000
Minimum Sales: 1000
Best Month for sales:    Month Sales
11   Dec  4000
Best Month for sales:   Month Sales
0   Jan  1000
Best Month for sales: Dec
Best Month for sales: Jan

In [27]:
# Employee Salary Analysis 5 employee 5 salaries find max salary,min salary and average salary with employee name.

employees_names = ["Ali", "Saad", "Usman", "Daud", "Ahmed"]
salaries = np.array([50000, 60000, 55000, 70000, 65000])

df_employees = pd.DataFrame({"Employee": employees_names, "Salary": salaries})
print(df_employees)

  Employee  Salary
0      Ali   50000
1     Saad   60000
2    Usman   55000
3     Daud   70000
4    Ahmed   65000

In [28]:
max_salary = df_employees["Salary"].max()
print("Maximum Salary:", max_salary)

min_salary = df_employees["Salary"].min()
print("Minimum Salary:", min_salary)

avg_salary = df_employees["Salary"].mean()
print("Average Salary:", avg_salary)

Maximum Salary: 70000
Minimum Salary: 50000
Average Salary: 60000.0

In [32]:
max_salary = df_employees["Salary"].max()
max_emp_idx = df_employees["Salary"].idxmax()
max_emp_name = df_employees.loc[max_emp_idx, "Employee"]
print(f"Employee with Max Salary: {max_emp_name}, Salary: {max_salary}")

min_salary = df_employees["Salary"].min()
min_emp_idx = df_employees["Salary"].idxmin()
min_emp_name = df_employees.loc[min_emp_idx, "Employee"]
print(f"Employee with Min Salary: {min_emp_name}, Salary: {min_salary}")

Employee with Max Salary: Daud, Salary: 70000
Employee with Min Salary: Ali, Salary: 50000

In [31]:
# debit card dataset Analysis send gpt to find all datasets methods and functions for data analysis in pandas.